[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scrabble"
version = "1.0.0"
description = "Scrabble multijugador cliente-servidor con Celery y Redis"
requires-python = ">=3.10"
dependencies = [
    "rich==15.0.0",
    "redis==8.1.0",
    "celery==5.6.3",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
]

[tool.setuptools.packages.find]
where = ["app"]
